// make verilog CONFIG=MinimalConfig MFC=1 WITH_CONSTANTIN=0 NO_ZSTD_COMPRESSION=1 IMAGE_GZ_COMPRESS=0 WITH_CHISELDB=0 EMU_TRACE=vcd NO_DIFF=1 XSTOP_PREFIX=XS_ RELEASE=1
${XS_REPO_DIR}/build/rtl/XSTop.v
${XS_REPO_DIR}/build/rtl/XS_array_0_0_ext.v
${XS_REPO_DIR}/build/rtl/XS_array_0_1_ext.v
${XS_REPO_DIR}/build/rtl/XS_array_0_2_ext.v
${XS_REPO_DIR}/build/rtl/XS_array_0_3_ext.v
${XS_REPO_DIR}/build/rtl/XS_array_0_4_ext.v
${XS_REPO_DIR}/build/rtl/XS_array_0_5_ext.v
${XS_REPO_DIR}/build/rtl/XS_array_0_6_ext.v
${XS_REPO_DIR}/build/rtl/XS_array_0_7_ext.v
${XS_REPO_DIR}/build/rtl/XS_array_0_ext.v
${XS_REPO_DIR}/build/rtl/XS_array_10_ext.v
${XS_REPO_DIR}/build/rtl/XS_array_11_ext.v
${XS_REPO_DIR}/build/rtl/XS_array_12_ext.v
${XS_REPO_DIR}/build/rtl/XS_array_13_ext.v
${XS_REPO_DIR}/build/rtl/XS_array_14_ext.v
${XS_REPO_DIR}/build/rtl/XS_array_15_ext.v
${XS_REPO_DIR}/build/rtl/XS_array_16_ext.v
${XS_REPO_DIR}/build/rtl/XS_array_17_ext.v
${XS_REPO_DIR}/build/rtl/XS_array_18_ext.v
${XS_REPO_DIR}/build/rtl/XS_array_1_ext.v
${XS_REPO_DIR}/build/rtl/XS_array_2_ext.v
${XS_REPO_DIR}/build/rtl/XS_array_3_ext.v
${XS_REPO_DIR}/build/rtl/XS_array_4_ext.v
${XS_REPO_DIR}/build/rtl/XS_array_5_ext.v
${XS_REPO_DIR}/build/rtl/XS_array_6_ext.v
${XS_REPO_DIR}/build/rtl/XS_array_7_ext.v
${XS_REPO_DIR}/build/rtl/XS_array_8_ext.v
${XS_REPO_DIR}/build/rtl/XS_array_9_ext.v
${XS_REPO_DIR}/build/rtl/XS_array_ext.v
